spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/pium?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&cacheDefaultTimezone=false
    username: root
    password: {MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

jwt:
  secret: {JWT_SECRET}

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: {S3_ACCESS_KEY}
      secret-key: {S3_SECRET_KEY}
    s3:
      bucket: {S3_BUCKET}

kakao:
  client-id: {KAKAO_CLIENT_ID}
  redirect-uri: {KAKAO_CALLBACK_URI}

  authorization-uri: {KAKAO_AUTH_URI}
  token-uri: {KAKAO_TOKEN_URI}
  user-info-uri: {KAKAO_USER_INFO_URI}